baseurl: "https://devf19.classes.ryansafner.com/"
languageCode: "en-us"
title: "Economics of Development"
theme: "ath-tufte-hugo_18-19"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Reference
      url: /reference/
      weight: 4
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Ryan Safner
  thumbnail: /images/econ_meta.png
  instructor: 
    name: Dr. Ryan Safner
    email: safner@hood.edu
    url: "https://www.ryansafner.com"
    twitter: ryansafner
    github: ryansafner
    office: 118 Rosenstock
  course:
    number: ECON 480
    semester: Fall 2019
    days: "MW"
    time: "11:30 AM–12:45 PM"
    location: "215 Rosenstock"
    twitter: ryansafner
    dates: >-
      August 26–December 10, 2019
    github: "ryansafner/devf19"
    #slack: "https://hoodeconometrics.slack.com/"
    copyrightYear: "2019"
    contactDetails: >-
      Office hours: MW 10:30--11:30AM
  university: 
    name: Hood College
    url: "https://www.hood.edu"
  school:
    name: George B. Delaplane, Jr. School of Business
    url: "https://hood.edu"
  description: "Understand and use economic reasoning to evaluate public policy"
  primaryColor: "#5E81AC"
  secondaryColor: "#D08770"
  credits: >-
    Hex icon by Ryan Safner via [hexSticker](https://github.com/GuangchuangYu/hexSticker).<br> Course website based on [Andrew Heiss](https://econw19.classes.andrewheiss.com/). <br>[Nord color scheme](https://github.com/arcticicestudio/nord) from [Arctic Ice Studio](http://arcticicestudio.com/).
  logo:
    url: /images/hoodmetrics.png
    alt: Econometrics
  meta:
    twitterSite: "@ryansafner"
    twitterCreator: "@ryansafner"
    fbAuthor: "https://www.facebook.com/ryansafner"
