---
title: "Assignments"
slug: assignments
---

- [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/dev_grade_calculator/)

Use this tool to calculate your final course grade and predict what grades you would need on remaining assignments to obtain a desired course grade.


# Country Profile {-}

Each of you will write a short profile of a different developing country and give a short presentation to the class. The countries that may be chosen will be restricted to developing economies in Latin America, Asia, Africa, and Eastern Europe. Students born outside of the U.S. may *not* choose the country of their birth. The purpose of this assignment is to "get you out of your comfort zone" and see the world from the perspective of a culture and an economy radically different than the one(s) you are familiar with.

# Participation and Discussion {-}

At the end of most lessons, we will hold a discussion. During our discussions, we will follow the rules pioneered and perfected by the Liberty Fund seminars.^[These rules are shamelessly adapted and modified from the highly-successful *Liberty Fund* seminars and from my colleagues Emily Chamlee-Wright, Joshua Hall, and Steve Horwitz.] I will provide you with a handout detailing the rules on the first discussion day. These discussions help shift the focus of the course away from me lecturing material at you more towards your learning and building upon material. This requires you to take ownership of your own learning. It is critical that you come to class having done the readings and are prepared for discussion. **You are required to email to me a list of 2-3 questions or points you want to discuss before class begins on each discussion day.** Everyone will receive a grade from 0-5 on each discussion day based on their participation. If I feel that students are not diligently doing the readings, *I reserve the right to implement readings-based quizzes and allocate some of the participation grade towards them.*

## General Information
 
At the beginning of each class, I may give a brief overview and background of the reading or the underlying topic. Then we will have a discussion for the remainder of class, unless otherwise specified. Please come on time and prepared to sit for that length of time. If you do need to step out, try to do so quietly. To the extent possible, we will have the desks arranged in a circle, so please help arrange them when directed. For the first few sessions, we may use nametags to to encourage mutual reference between discussion participants, e.g., "I want to respond to something John said earlier..."
 
## Discussion Rules
 
I as the instructor will begin by highlighting some points within the readings and posing questions to which discussion participants might wish to respond. Those introductory remarks should take no more than 5 minutes, leaving the balance of the discussion time for participants to respond to those queries, present your own questions, and respond to other discussion participants. This means that you are duty-bound to come prepared, with the text read carefully, with notes and/or questions written down so that you can contribute to a lively and engaged discussion.
 
After I finish my introductory remarks, the "queue" is then opened for participants to respond and/or pose their own questions. I will keep the queue and acknowledge whose turn it is to speak. You may indicate your interest in making a comment by raising your hand upward. If, while another discussion participant is speaking you decide that you would like to make your own points, you should ``catch my eye'' by raising your hand quietly, and wait for a silent nod indicating that you have been placed on the queue. I will periodically remind everyone who is in line to speak.
 
If discussion participants wish to make a very brief comment that pertains to something that was just said, you can be put on the "brief comment queue which allows you to get your short point in right away before the conversation moves too far beyond the specific issue being raised. Participants wishing to be put on the short comment queue indicate this by putting their finger and thumb together (as if to say, "this will be short, I promise.") A position within the brief comment queue does not eliminate a position in the main queue. This helps to assure that brief comments remain brief and that participants will have time to articulate their longer points when their turn in the long comment queue comes around.
 
I may participate in both queues, but I will have to abide by the same rules as everyone else (i.e., I have to wait my turn just like everyone else). I also reserve the right to change the order of the queue to make sure that everyone who wants to speak gets the chance. This may include moving people up the queue who have not spoken yet before someone else speaks for a second or third time. I also reserve the right to cut short comments that go on too long and to take other appropriate measures necessary to maintaining order and decorum.
 
Mutual respect is an absolute in these discussions. That said, one can be respectful while still engaging in lively argument. Striking this balance is the key to a successful discussion and is the responsibility of everyone at the table.
 
## Grading Policy
 
Each discussion day, students will earn 0 to 5 points. While it is perfectly acceptable to not speak on any given discussion day, consecutive discussion days with no active participation will earn successively lower scores.

- **0**: For students who are not present (without a legitimate excuse) on a discussion day.
- **1**: For students who do attend but appear inattentive or disengaged from the discussion.
- **2**: For students who attend and do not say anything, but who appear to be engaged and are focused on the conversation. (Now, I know what you are thinking. ``How does he know whether I am engaged or disengaged? He cannot read my thoughts!'' True enough. But I can tell whether or not you appear to be engaged and this makes a difference. A student who appears to be disengaged creates a negative externality that causes the slow death of what might otherwise have been a lively discussion. Students who appear to be engaged, even if they are silent, encourage others to continue their active participation, hence the 3 points.)
- **4**: For students who speak up a few times during the course of the discussion.
- **5**: For students who offer frequent thoughtful commentary, connects their comments to the comments of others, sparks debate, etc.

## Questions and Grading

You are required to come up with 2-3 questions or topics prior to the discussion that they wish to discuss. These must be **emailed to me before** a discussion. These questions are to be substantive, and meant to provoke discussion. No questions that either evidence that students' have not done the reading, or simple definitional questions that can be answered in a sentence (e.g. "what does Adam Smith say the division of labor is?"). 

Your "questions" need not be in the form of a question -- some suggestions are putting provocative claims or an argument out there and seeing what others think, bringing in a topic from current events or your daily life that is relevant to the topic, or connecting the topic or readings to other courses you have taken. Ideally, your questions will be directed towards the readings, but they may cover anything broadly connected to the week's topic.

- Good questions that are provocative and/or demonstrate careful reading can **add +1 point** to a discussion grade. This encourages students who might be a bit shy to talk during discussion to get something better than a 3 for a day.^[You can earn a 6 out of 5 points for days where you have very good questions and participate very well. I try to give these out sparingly.]
- Not turning in questions, turning in questions *after class begins*, or having questions that are too simplistic or demonstrate a lack of reading can **subtract -1 point** to a discussion grade. This is to penalize those of you who may be able to get by with talking a lot (earning a 5) but clearly have not done the readings.

The main purpose of the questions is to provide evidence that students are doing the readings and are prepared to talk about them, so bear this in mind. 

At the end of the semester, I will take an average by adding up your total accumulated score and divide it by the number of discussion days we had. This average score will constitute your participation grade for the course. 

# Short Papers {-}

There will be two short papers on assigned topics. The first will be early in the semester, covering topics from the first several weeks. The second will cover topics from the remaining weeks. I am looking for 3-5 page papers that explore subjects prompted by questions that I will provide to you in advance. However, I also encourage you to take the less-trodden path and explore something unique and interesting to you.

# Final exam {-}

The take-home final exam will be a series of essay questions.