---
title: "2. Measuring Development - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

**Updated Wednesday, September 4, 2019**

# Recommended Readings:

- [<i class="fas fa-file-pdf"></i> Sen (1988), "The Concept of Development"](/readings/sen-1988-concept-of-development.pdf)
- [<i class="fas fa-file-pdf"></i> Boettke and Subrick (2003), "Rule of Law, Development, and Human Capabilities"](/readings/Boettke-Subrick-2003.pdf)
- [<i class="fab fa-youtube"></i> TED Talk: Hans Rosling on the Best Stats You've Ever Seen](https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen)
- [<i class="fab fa-youtube"></i> BBC: Hans Rosling's 200 Countries, 200 Years, 4 Minutes](https://www.youtube.com/watch?v=jbkSRLYSojo)
- [<i class="fab fa-youtube"></i> TED Talk: Hans Rosling on the Magic Washing Machine](https://www.ted.com/talks/hans_rosling_and_the_magic_washing_machine)


We will not have a discussion on these readings for this lesson. However, they may come up in future discussions and provide a good framework for understanding development going forward.

Amartya Sen's "capabilities approach" to "development as freedom" is a good way to think about economic development beyond just GDP numbers. The reading summarizes his views that are famously expounded in a larger book (*Development as Freedom*).

Boettke and Subrick's paper shows (with some modest econometrics) that capabilities are strongly affected by economic development, so GDP numbers remain a great tool.

I highly recommend you watch all of Hans Rosling's videos. They are amazing.