---
title: "7. Geography and Uncontrollable Factors - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required Readings:

- <i class="fas fa-book"></i>Chapter 2 in @Acemoglu2008
- [<i class="fas fa-file-pdf"></i> Sachs, Mellinger, and Gallup (2001), "The Geography of Poverty"](/readings/Sachs-Mellinger-Gallup-2001.pdf)

Acemoglu and Robinson's work is famous for arguing that *institutions* are the fundamental cause of differences in income and growth around the world. This chapter argues that other theories--geography, culture, and ignorance--are insufficient to explain the differences.

Sachs, Mellinger, and Gallup are famous for papers emphasizing the role of geography in determining economic development. This is a short article in *Scientific American* written for a popular audience that summarizes their research.  

# Primary Sources

- [<i class="fas fa-file-pdf"></i> Gallup, Sachs, and Mellinger (1999), "Geography and Economic Development"](/readings/Gallup-Sachs-Mellinger-1999.pdf)
- [<i class="fas fa-file-pdf"></i> Mellinger, Sachs, and Gallup (1999), "Climate, Water Navigability, and Economic Development"](/readings/Gallup-Sachs-Mellinger-1999.pdf)
- [<i class="fas fa-file-pdf"></i> Sachs and Warner (2001), "The Curse of Natural Resources"](/readings/Sachs-Warner-2001.pdf)
- [<i class="fas fa-file-pdf"></i> Sachs, Mellinger, and Gallup (2001), "The Geography of Poverty"](/readings/Sachs-Mellinger-Warner-Gallup.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu, Johnson, and Robinson (2002), "The Reversal of Fortune"](/readings/Acemoglu-Johnson-Robinson-2002.pdf)
- [<i class="fas fa-file-pdf"></i> Rodrik, Subramanian, and Trebbi (2002), "Institutions Rule: The Primacy of Institutions Over Geography and Integration in Economic Development"](https://www.nber.org/papers/w9305.pdf) 
- [<i class="fas fa-file-pdf"></i> Comin, Easterly, and Gong (2010), "Was the Wealth of Nations Determined in 1000 BC?"](/readings/Comin-Easterly-Gong-2010.pdf)
- [<i class="fas fa-file-pdf"></i> Spolaore and Wacziarg (2013), "How Deep are the Roots of Economic Development"](/readings/Spolaore-Wacziarg-2013.pdf)
- [<i class="fas fa-file-pdf"></i> Alsan (2015), "The Effect of the Tse Tse Fly on African Development"](/readings/Alsan-2015.pdf)


# Questions to Read For:

- How much do of a role do you think geography (however construed) plays in helping or hurting economic development? Can countries with favorable geography fail to grow? Can countries with unfavorable geography succeed despite it?

- Do you believe there is a "natural resource curse?" Is it inevitable?

- Now that you understand the resource curse, do you believe *foreign aid* is similar to the resource curse? Recall from last lesson that Ovaska (2003) argues aid is *worse* than the curse of resources!

- Perhaps geography *used* to matter a lot for development when transaction costs were historically prohibitively high. But with today's technology and infrastructure, is geography as much of a factor as it may have once been? Why or why not?

- How might geography influence institutions?

- Some countries have unfavorable geography due to being landlocked, consisting of unproductive marshland, or are endowed with no resources, yet are incredibly wealthy today (e.g. Switzerland, Luxemborg, Singapore). How can we explain this?

- If you believe geography is important for determining economic development, is Africa uniquely disadvantaged for development because of its geography? If so, does it require foreign aid for growth to overcome these disadvantages?

- Acemoglu and Robinson argue against not only what they call "the geography hypothesis" but also the "culture hypothesis" and the "ignorance hypothesis" as explanations for variation in income per capita around the world today. What are each of these hypotheses? How do Acemoglu and Robinson argue they are problematic? Do you agree or disagree?

- What is the "reversal of fortune" that Acemoglu and Robinson talk about? If we go back to 1500, what types of geography did all world's wealthy civilizations share? What about poor civilizations? Why the major reversal? What is the role of institutions in this reversal?