---
title: "8. Political Economy - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required Readings:

- <i class="fas fa-book"></i>Chapter 3 in @Acemoglu2008

Chapter 3 outlines the central thesis of the book: that differences in income per capita around the world today, and the trajectories of economic development are determined by political and economic institutions. AJR^[The common nickname for "Acemoglu, Johnson, and Robinson", who frequently collaborate on these issues (see the primary sources below).] distinguish between "inclusive institutions" and "extractive institutions," and describe how the distribution of political power affects political institutions, which in turn affect economic institutions, which affects a nation's ability to sustain economic growth.  

# Strongly Recommended

- <i class="fas fa-book"></i>Chapter 1 in @Acemoglu2008

Chapter 1 sets the stage with a number of stories that emphasize the differences in inclusive vs. extractive institutions, primarily by comparing the colonization experience of the Spanish in South/Central America and the English in North America.

# Primary Sources

- [<i class="fas fa-file-pdf"></i> Stigler (1971), "The Theory of Economic Regulation"](/readings/Stigler-1971.pdf)
- [<i class="fas fa-file-pdf"></i> Kreuger (1974), "The Political Economy of the Rent-Seeking Society"](/readings/Kreuger-1974.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu and Robinson (2000), "Political Losers as a Barrier to Economic Development"](/readings/Acemoglu-Robinson-2000.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu, Johnson, and Robinson (2001), "The Colonial Origins of Comparative Development: An Empirical Investigation"](/readings/Acemoglu-Johnson-Robinson-2001.pdf)
- [<i class="fas fa-file-pdf"></i> Acemoglu and Johnson (2005), "Unbundling Institutions"](/readings/Acemoglu-Johnson-2005.pdf)
- [<i class="fas fa-file-pdf"></i> Baumol (1990), "Entrepreneurship: Productive, Unproductive, and Destructive"](/readings/Baumol-1990.pdf)
- [<i class="fas fa-file-pdf"></i> Tullock (1967), "The Welfare Cost of Tariffs, Monopolies, and Theft"](/readings/Tullock-1967.pdf)
- [<i class="fas fa-file-pdf"></i> Alchian (1950), "Uncertainty, Evolution, and Economic Theory"](/readings/Alchian-1950.pdf)
- [<i class="fas fa-file-pdf"></i> Murphy, Shleifer, Vishny (1991), "The Allocation of Talent: Implications for Growth"](/readings/Murphy-Shleifer-Vishny-1991.pdf)
- [<i class="fas fa-file-pdf"></i> Glaesar et. al (2004), "Do Institutions Cause Growth?"](/readings/Glaesar-et-al-2004.pdf)


# Questions to Read For:

- According to Acemoglu and Robinson, what is the difference between "inclusive" institutions and "extractive" institutions?

- What causes 