---
title: "9. The Pre-Modern Malthusian World - Readings"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required Readings:

- [<i class="fas fa-book"></i>Chapter 1 in Scott (1999) *Seeing Like a State*](/readings/Scott-1999-Ch1.pdf)
- [<i class="fas fa-file-pdf"></i> Olson (1993), "Dictatorship, Democracy, and Development"](/readings/Olson-1993.pdf)

James Scott is a political scientist and anthropologist who specializes in agrarian and non-State societies. This is one of several provocative books, but the main contribution of this particular book (and chapter) is to highlight the lack of state capacity and its implications. It will really give you a detailed description of how States require "legibility" to command and control resources, and just how illegible societies really are, particularly before the rise of powerful States. I also strongly recommend Slate Star Codex's review of the book (see below) to give you the full picture in an accessible manner.

Second, Mancur Olson's work is a very famous model that describes the different incentives of dominant groups that wield political power (i.e. the State) and how that affects economic development. Think about how Acemoglu and Robinson's inclusive vs. extractive institutions fit into Olson's model (which came first).

Overall, we will be considering economic history from the very beginning of human society up through the modern era. This was characterized by Malthusian population pressures, so we will explore this as well.

# Recommended

- [<i class="fas fa-external-link-square-alt"></i> Alexander, (2017), "Book Review: Seeing Like a State" (Slate Star Codex blog)](https://slatestarcodex.com/2017/03/16/book-review-seeing-like-a-state/)
- [<i class="fab fa-youtube"></i> Bill Wurtz: history of the entire world i guess](https://www.youtube.com/watch?v=xuCn8ux2gbs)
- [<i class="fas fa-external-link-square-alt"></i> Diamond, (1987), "The Worst Mistake in the History of the Human Race"](http://discovermagazine.com/1987/may/02-the-worst-mistake-in-the-history-of-the-human-race)
- [<i class="fas fa-podcast"></i> NPR's *Planet Money*: "A Bet On The Future Of Humanity"](https://www.npr.org/sections/money/2018/01/19/579192124/episode-508-a-bet-on-the-future-of-humanity)
- [<i class="fas fa-podcast"></i> *Economics Detective Radio*: "The Second Ehrlich-Simon Wager with Joanna Szurmak"](https://economicsdetective.com/2016/11/second-ehrlich-simon-wager-joanna-szurmak/)

Silly as it is, I recommend watching Bill Wurtz' amazing "history of the entire world i guess," to give you some proper context of the broad stretches of history we'll ultimately be covering.

Additionally, as Malthusian pre-modern economies are primarily subsistence agriculture, we should consider the impact that farming has had on humans. See Jared Diamond's provocative argument for all the downsides of the Neolithic Revolution (the human transition from nomadic hunter-gatherers to settled agriculture about 12,000 years ago). This also fits into Olson's argument.

The last two are podcasts on the Simon-Ehrlich wager. The first (*Planet Money*) is a good description of what happened, the second (*Economics Detective Radio*) is a great interview with an economist working on what might have happened for the *second* proposed sequel to the bet (and gets into the differences Ehrlich and Simon had in worldviews).

# Primary Sources

- [<i class="fas fa-external-link-square-alt"></i> Malthus, (1798), "An Essay on the Principle of Population"](https://www.econlib.org/library/Malthus/malPop.html)
- [<i class="fas fa-file-pdf"></i> Kremer (1993), "Population Growth and Technological Change: One Million B.C. to 1990"](/readings/Kremer-1993.pdf)


# Questions to Read For:

- Most theories of the state in the classical liberal Western tradition of political philosophy (Thomas Hobbes, John Locke, Thomas Jefferson & James Madison, John Rawls) suppose a "social contract" as the origin of the State - the agent that protects our rights. Olson (and others, we will see) argue the social contract is a fiction, and is not how states *actually* emerged. What are we to make of this?

- What is the difference between a roving bandit and a stationary bandit (in Olson's model)? How does one become the other? Which societies today look like which form?

- What is the difference betwee the State and the Mafia? 

- What parallels do you see between historical societies that are ruled by roving vs. stationary bandits, and societies today?

- In Olson's language, which socities today are ruled by "roving bandits" versus "stationary bandits?" How, specifically, does that affect their level of development?

- What is State capacity, and why is it necessary for economic development?

- What is James Scott's metaphor with "scientific forestry," and how does it have to do with the "legibility" of society and State capacity?

- What does it mean, according to Scott, to "see like a State." Why is this so difficult?

- What parallels do you see between historical societies (e.g. Medieval Europe) with low state capacity or "illegibility" and developing countries today?