---
title: "Lesson 4: The Microeconomics of Development - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Overview

We begin with our approach to trying to "model" development. We begin at the micro-level and begin with the original - Adam Smith. We cover major concepts that are key tohow prosperity grows (division of labor, transition from subsistence to exchange, etc) and how markets work. In exploring markets (much in the way you would in ECON 306), we highlight the role of prices and entrepreneurship in bringing about coordination and progress - in doing so, we apply Hayek's answer to the socialist calculation debate of the previous lesson.

There are no formal "models" here, only major concepts, but they are coming in the next lesson, which takes a more macroeconomic view towards understanding, modeling, and stimulating economic growth. *This* lesson will have no discussion, I will lecture for 2 class periods. Our next lesson, which may take 1-3 class periods, will end in a discussion on all of these concepts and models.

In thinking about how to "model" an economy in a way that policymakers can exploit (e.g. manipulate key choice variables that can be changed) and assess the results, consider again: what exactly are we able to control? What knowledge must policymakers possess? What incentives ensure it gets implemented "the way we want?"

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/04-slides.html)

# Readings

See this week's [readings page](/reading/04-reading) for *recommended* readings, as there will be no formal discussion this week. I still encourage you to look at them. Note *next week's required* readings will require you to have the textbooks!

# Discussion Grades

Discussion/participation grades from the combination of your emailed questions and discussion participation (out of 5 points) for last week's discussion will be posted on Blackboard shortly. 
