---
title: "Lesson 4: The Macroeconomics of Development - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Overview

Here we explore the famous growth models of an economy. This lesson will be the most technical of the semester, but remember there are no homeworks or exams that have you use the models to calculate equilibrium outcomes. It is more important that you understand the basic mechanisms and the major conclusions of hte models. Modern economic development, macroeconomics, and public policy literatures rely heavily on these models!

We begin with a history of economic thought on growth, from the classicals through the famous neoclassical models and their extensions in the 1950s-1980s. Before we reach the major models, we mention, among others, David Ricardo for his insistence on diminishing returns and the steady state, the Harrod-Domar model for the first major milestone in growth modeling, and Nicholas Kaldor for his famous "stylized facts" that growth models must explain.

We look first at the famous Solow model, or "exogenous growth" model of Robert Solow. Physical capital plays a central role in the model, requiring an economy to accumulate an optimal stock of physical capital (relative to labor) in order to achieve a steady-state growth path. The more surprising element is that growth in output empirically is explained almost entirely (about 80%) by achievements in "technology" or "total factor productivity (TFP)," the unmeasurable "Solow residual." In these models, the growth of TFP is given *exogenously.*

We later turn to the famous Romer model, or "endogenous growth" model of Paul Romer (and coauthors). Here (inside a Solow-type model) TFP is something economies (firms and governments) can *explicitly* invest in (via R&D, education, etc.) to determine TFP *endogenously*.

In thinking about how to "model" an economy in a way that policymakers can exploit (e.g. manipulate key choice variables that can be changed) and assess the results, consider again: what exactly are we able to control? What knowledge must policymakers possess? What incentives ensure it gets implemented "the way we want?"


# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/05-slides.html)

# Readings

See this week's [readings page](/reading/05-reading) for *required* readings for our discussion.

# Math Appendices

## Cobb-Douglas Functions

A Cobb-Douglas function takes the form: 

$$y=Ax_1^\alpha x_2 ^\beta$$

It is often used for utility functions $(y$ is utility, $x_1$ and $x_2$ are goods) and production functions $(y$ is output, $x_1$ and $x_2$ are factors of production, such as $L$ and $K).$

It is often converted into logarithmic form by taking the natural logs:

$$ln \, y = ln \, A + \alpha \, ln \, x_1 + \beta \, ln \, x_2$$

This function is (surprisingly) easy to work with for its many useful properties:

1. Returns to scale
    - If $\alpha+\beta > 1$: increasing returns to scale
    - If $\alpha+\beta = 1$: constant returns to scale
    - If $\alpha+\beta < 1$: decreasing returns to scale

2. Elasticities/Shares
    - In the constant returns to scale case (the exponents sum to 1), often rewritten as $y=Ax_1^{\alpha}x_2^{1-\alpha}$:
        - $\alpha$ represents the (fraction of income spent - in utility case; output elasticity - in production case) of each $x_i$
            - e.g. if $u=x^{0.4}y^{0.6}$, consumer spends 40% of income on $x$ and 60% on $y$
            - e.g. if $y=K^{0.4}L^{0.6}$, a 1% increase in $K$ generates a $0.4$% increase in $y$
            - Aggregate Production Function case: $\alpha$ is the "share" of output or income going to each factor

3. Desirable shape of function
    - Convex
    - Positive but diminishing returns to each $x_i$, $\left(\frac{\partial y}{\partial x_i} > 0, \, \frac{\partial^2 y}{\partial x_i^2} < 0 \right)$

See more on Cobb-Douglas functions from my ECON 306 - Microeconomic Analysis course notes:

- [Cobb Douglas Utility Functions](https://microf19.classes.ryansafner.com/class/08-class/#cobb-douglas)
- [Consumer's Constrained Optimization with Cobb-Douglas](https://microf19.classes.ryansafner.com/class/06-class/#solving-the-constrained-optimization-problem-with-calculus)
- [Deriving Demand from Cobb-Douglas Utility](https://microf19.classes.ryansafner.com/class/08-class/#cobb-douglas)

For production, simply replace $u$ with $y$, and $x$ and $y$ with $l$ and $k$.

## Growth Accounting

Take the production function of the general form: 
$$Y=f(A,L,K)$$
where $Y$ is output, $K$ is total capital stock, $L$ is total labor, and $A$ is TFP. 

Take standard assumptions about $f$: it is increasing in $A$, $L$, & $K$, and is homogenous of degree 1 (constant returns to scale), so we can assume perfect competition, whereby:

$$\begin{align*}
\frac{dY}{dK}=MP_K&=r\\
\frac{dY}{dL}=MP_L&=w\\
\end{align*}$$

Totally differentiate the production function:

$$dY=F_A dA+F_K dK + F_L dL$$

where $F_i$ denotes the partial derivative of $F$ w.r.t. factor $i$, aka the marginal product of $i$. With perfect competition, this becomes:

\begin{align*}
dY&=F_A dA + MP_K dK+ MP_L dL\\
dY&=F_A dA + r dK + w dL\\
\end{align*}

Divide by $Y$ and convert each change into growth rates:

$$\frac{dY}{Y}=\left(\frac{F_A A}{Y}\right)\left(\frac{dA}{A}\right)+\left(\frac{rK}{Y}\right)\left(\frac{dK}{K}\right)+\left(\frac{wL}{L}\right)\left(\frac{dL}{L}\right)$$

Now, denote the growth rate (% change over time) of each factor $i$ as $g_i=\frac{di}{i}$:

$$g_Y=(\frac{F_A A}{Y})*g_A + (\frac{rK}{Y})*g_K+(\frac{wL}{Y})*g_L$$

Then $\frac{rK}{Y}$ is the share of total income that goes to capital, denoted $\alpha$, and $\frac{wL}{Y}$ is the share that goes to labor, denoted as $1-\alpha$. Re-express the equation as:

$$g_Y=\frac{F_A A}{Y}*g_A+ \alpha g_K+(1-\alpha)g_L$$

In principle, $\alpha, g_Y, g_L$ are observable, but the Solow residual term $\frac{F_A A}{Y}$ isn't. We can measure it as the portion of increase in total income not accounted for by (weighted) growth of factor inputs:

$$SolowResidual=g_Y-\alpha g_K-(1-\alpha)g_L$$