---
title: "Lesson 9: The Pre-Modern Malthusian World - Class Notes"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-syllabus-no-bib.csl
output:
  blogdown::html_page:
    template: ../../pandoc/toc-title_html.template
    toc: true
editor_options: 
  chunk_output_type: console
---

# Overview

This week we continue our discussion of economic history under low state capacity and discuss two aspects. 

First, what were most "States" like before the modern era? We know they are unable to tax or do very much by modern standards, but it certainly was not pure anarchy. For nearly all of human history since settled agriculture, people have (at least nominally) been the subjects of an autocrat^[This is a catch-all term for a non-democratically-elected ruler, such as a king/queen, emperor/empress, dictator, etc.] of some sort. Olson provided us with one framework for understanding the incentives of the ruler: a revenue-maximizing stationary bandit, which is preferable to the anarchy of roving bandits. We consider two other models - so called "selectorate theory" and the "natural state."

Second, we consider why countries today do not suddenly switch from autocracy to democracy, or, when they try to, they often revert right back into autocracy (consider the famed Arab Spring and its aftermath). This is the idea of the "violence trap," that a sub-optimal equilibrium is stable, and even if a more-preferable equilibrium is within sight, the transition to get there is fraught with peril and violence (perhaps a period of roving bandits?), and worse than the sub-optimal eequilibrium.

# Slides

- [<i class="fas fa-external-link-square-alt"></i> Lecture Slides](/slides/10-slides.html)

# Readings

See this week's [readings page](/reading/10-reading) for *required* readings for our discussion.
