---
title: "Short Paper 2"
editor_options: 
  chunk_output_type: console
---

```{r message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(pander)
source(file.path(here::here(), "lib", "graphics.R"))
```

- *Due 8:00 PM Friday, December 6 by email*

# Overview 

This assignment is the same as short paper 1. Please see [that assignment's page](/assignment/01-short-paper) for reminders about structure and grading.


## Potential Topic Prompts

I would prefer for you to choose a topic from lesson 8 onwards. Again, you are free to choose your own topic, and might wish to write about something similar to your first short paper or something based on some of the comments and feedback I gave you. 

Here are a few **suggestions**, based on trains of thought that I think would be interesting, or ideas that I myself am currently grappling with. You are welcome to use these as motivating questions or jumping-off points to develop your own thoughts on an issue, *just make sure to write a paper that has a reasonably clear thesis and argument.* **Do not think of these as a required set of questions that you must choose and specifically answer (i.e. this is not an exam)**. In fact, each bullet point contains multiple related questions, any one of which might spark a separate interesting paper.

**You are _not_ required to pick one of these questions**. That is, you can write on your own topic that is interesting to you so long as it is relevant and builds off of what we have discussed so far. One suggestion would be to take a discussion question that you turned in or found interesting from the readings and lectures as a jumping off point.

1. What is the role of [Event X] in forming the institutions necessary for the industrial revolution, economic growth, and development in Western Europe? Where X could be:
  - The Protestant Reformation
  - The Black Death
  - The Plague

2. How should we assess the record of imperialism in terms of affecting economic development?

3. Mercantilism, to the extent it is studied, in economics courses is often a poster child of "what trade policies a country *should not* have," and most economics courses spend time covering the negative economic consequences of tariffs, trade restrictions etc. Now that you have a bit more context and the economic-historical trajectory of Western institutions towards liberal democracy, how should we view Mercantilism?

4. Feudalism often refers specifically to the Medieval Era in Europe (c. 500-1500), and very clearly is a limited access order. While due to time constraints, we could only focus on so many regions of the world, we looked primarily at Europe. In what way does studying feudalism also shed insight into economic history in other parts of the world?

5. Ludwig von Mises argued in 1920 that rational economic calculation in a socialist commonwealth is impossible (Recall Lesson 3!). The Soviet Union lasted for about 70 years (1921-1991). Was Mises wrong? Or was Soviet socialism not a true socialist commonwealth? How did the economy and central planning actually work?

6. What do you think went right, and what went wrong, in the transition from Communism in Eastern Europe and Russia, towards liberal democracy and markets? Was what happened destined to happen?

7. How do remnants of feudalism still exist in our culture, economy, politics, or law today?

8. A lot of mercantilist tropes and policy ideas remain popular today ("Buy American," our country needs to to win at trade", "tariffs protect American workers," obsessions over the balance of trade and fixing trade deficits, etc.). Why do you think this remains popular in the minds of the people and/or political leaders? Why do you think some such policies are still in existance?

9. Our discussions of political institutions and institutional change, and the models we consult, might be considered an *elite* theory of changes: reforms and institutional changes must be incentive-compatible and in the interest of the elite. With all of the democratic mythos, and focus on the American people, how would you view the origin of the United States as an independent nation?